In [10]:
import pandas as pd

from helpsk.utility import read_pickle
from helpsk.logging import Timer

In [11]:
ngrams_low = 1
ngrams_high = 3
num_clusters = 10

In [12]:
with Timer("Loading Data"):
    path = '/code/artifacts/data/processed/un_debate_paragraphs.pkl'
    paragraphs = pd.read_pickle(path)
    paragraphs = paragraphs.sample(5000, random_state=42)
    
with Timer("Loading TF-IDF vectorizer/model via NMF"):
    _file = f'/code/artifacts/models/topics/nmf-topics-{num_clusters}-ngrams-{ngrams_low}-{ngrams_high}__vectorizer.pkl'
    tfidf_vectorizer = read_pickle(_file)

    _file = f'/code/artifacts/models/topics/nmf-topics-10-ngrams-{ngrams_low}-{ngrams_high}__vectors.pkl'
    tfidf_vectors = read_pickle(_file)
    
    _file = f'/code/artifacts/models/topics/nmf-topics-{num_clusters}-ngrams-{ngrams_low}-{ngrams_high}__model.pkl'  # noqa
    tfidf_model = read_pickle(_file)

with Timer("Loading Count vectorizer/model via LDA"):
    _file = f'/code/artifacts/models/topics/lda-topics-{num_clusters}-ngrams-{ngrams_low}-{ngrams_high}__vectorizer.pkl'
    count_vectorizer = read_pickle(_file)

    _file = f'/code/artifacts/models/topics/lda-topics-{num_clusters}-ngrams-{ngrams_low}-{ngrams_high}__vectors.pkl'
    count_vectors = read_pickle(_file)
    
    _file = f'/code/artifacts/models/topics/lda-topics-{num_clusters}-ngrams-{ngrams_low}-{ngrams_high}__model.pkl'  # noqa
    count_model = read_pickle(_file)

In [13]:
paragraphs.head()

year                   country  \
228015  2006       Palestine, State of   
113526  1988                    Turkey   
224796  2006  Central African Republic   
130703  1991                    Sweden   
59553   1980                Mozambique   

                                                     text  
228015  Indeed, I need not reconfirm the fact that, af...  
113526  With this understanding we have initiated a di...  
224796  The recent conference on AIDS, held here at \n...  
130703  The Swedish Government strongly supports the e...  
59553   76.\tDue to the tolerance shown to South Afric...

# Cosine Similarity - TF-IDF

In [14]:
paragraphs

year                   country  \
228015  2006       Palestine, State of   
113526  1988                    Turkey   
224796  2006  Central African Republic   
130703  1991                    Sweden   
59553   1980                Mozambique   
...      ...                       ...   
140522  1993                      Cuba   
166859  1996                Mauritania   
99907   1986                Luxembourg   
210583  2003                Luxembourg   
236034  2008                   Germany   

                                                     text  
228015  Indeed, I need not reconfirm the fact that, af...  
113526  With this understanding we have initiated a di...  
224796  The recent conference on AIDS, held here at \n...  
130703  The Swedish Government strongly supports the e...  
59553   76.\tDue to the tolerance shown to South Afric...  
...                                                   ...  
140522  The new international economic order, three\ni...  
166859  It is gratifying to note that, as the Organiza...  
99907   Our third cause for concern is undoubtedly con...  
210583  As was recently noted by the Secretary-General...  
236034  The same applies to disarmament policy. Only a...  

[5000 rows x 3 columns]

In [49]:
from sklearn.metrics.pairwise import cosine_similarity

# note we need to build a pipeline that cleans not just the training data but also new data if we want to use it for *search*
# This would also ensure consistency e.g. i accidently used text_clean instead of all_lemmas    
example = paragraphs['text'].iloc[0]
example

'Indeed, I need not reconfirm the fact that, after \nthe experiences of war and suffering that we have been \nthrough, unless the question of Palestine and that of the \ncontinuing occupation of Palestinian and Arab lands \nsince 1967 is resolved, the elements of tension and \nconflagration will keep the conflict alive and leave the \ndoor wide open to all forms of violence, terrorism, \nregional confrontations and global crises'

In [50]:
example_vector = tfidf_vectorizer.transform([example])
example_vector.shape

(1, 7852)

In [51]:
# calculate cosine similarity between the original vectors (i.e. tfidf_vectors) and our example
example_cosine_sim = cosine_similarity(tfidf_vectors, example_vector)
example_cosine_sim = example_cosine_sim.reshape(1, -1)[0]
example_cosine_sim.shape

(5000,)

In [75]:
top_n = 10
_temp_sample = paragraphs.copy()
_temp_sample['similarities'] = example_cosine_sim

top_n_examples = _temp_sample.sort_values('similarities', ascending=False).head(top_n)
assert round(top_n_examples['similarities'].iloc[0], 4) == 1

In [76]:
print(top_n_examples['text'].iloc[0])

Indeed, I need not reconfirm the fact that, after 
the experiences of war and suffering that we have been 
through, unless the question of Palestine and that of the 
continuing occupation of Palestinian and Arab lands 
since 1967 is resolved, the elements of tension and 
conflagration will keep the conflict alive and leave the 
door wide open to all forms of violence, terrorism, 
regional confrontations and global crises


In [77]:
print(top_n_examples['text'].iloc[1])

49.	The international community unanimously recognizes that a just and lasting peace cannot be achieved if it does not include the basic elements that we have just set forth. But the Zionist entity, which professes to want peace, arrogantly and obstinately opposes this unanimous will of the international community and continues its aggression and its occupation of Palestine and other independent and sovereign Arab countries neighbouring Palestine. Moreover, the decision taken on 16 September last by the Council of Ministers of Israel, under which Israelis will be allowed to acquire Arab lands and property on the West Bank and in Jerusalem, again confirms Israel's determination to pursue its policy of Occupation and aggression and to undermine the chances for a just and lasting peace in the area


In [78]:
pd.set_option('display.max_colwidth', 300)
top_n_examples[['year', 'country', 'text', 'similarities']].\
    style

---

# Cosine Similarity - Embeddings

In [81]:
from sentence_transformers import SentenceTransformer, util
model = SentenceTransformer('multi-qa-MiniLM-L6-cos-v1')

In [29]:
paragraph_embeddings = model.encode(paragraphs.text.tolist())
paragraph_embeddings.shape

(5000, 384)

In [38]:
query_embedding = model.encode(paragraphs.text.tolist()[0])
similarities = util.dot_score(query_embedding, paragraph_embeddings)[0]
similarities

tensor([1.0000, 0.3442, 0.3606,  ..., 0.3995, 0.2873, 0.3785])

---

In [114]:
cosine_sims = cosine_similarity(paragraph_embeddings, query_embedding.reshape(1, -1))
# looks like cosine_similarity and dot_score return same thing
print(cosine_sims[0:5].reshape(1, -1))
print(similarities[0:5])

[[1.         0.34419763 0.3605953  0.36372387 0.19492552]]
tensor([1.0000, 0.3442, 0.3606, 0.3637, 0.1949])


---

In [70]:
top_n = 10
_temp_sample = paragraphs.copy()
_temp_sample['similarities'] = similarities
top_n_examples = _temp_sample.sort_values('similarities', ascending=False).head(top_n)
assert round(top_n_examples['similarities'].iloc[0], 4) == 1

In [74]:
pd.set_option('display.max_colwidth', 300)
top_n_examples[['year', 'country', 'text', 'similarities']].\
    style

---